// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: oss-proto/oss.proto

package oss

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PreSignedRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PreSignedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreSignedRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreSignedRequestMultiError, or nil if none found.
func (m *PreSignedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PreSignedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Category

	// no validation rules for Name

	if len(errors) > 0 {
		return PreSignedRequestMultiError(errors)
	}

	return nil
}

// PreSignedRequestMultiError is an error wrapping multiple validation errors
// returned by PreSignedRequest.ValidateAll() if the designated constraints
// aren't met.
type PreSignedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreSignedRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreSignedRequestMultiError) AllErrors() []error { return m }

// PreSignedRequestValidationError is the validation error returned by
// PreSignedRequest.Validate if the designated constraints aren't met.
type PreSignedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreSignedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreSignedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreSignedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreSignedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreSignedRequestValidationError) ErrorName() string { return "PreSignedRequestValidationError" }

// Error satisfies the builtin error interface
func (e PreSignedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreSignedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreSignedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreSignedRequestValidationError{}

// Validate checks the field values on PreSignedReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PreSignedReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreSignedReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PreSignedReplyMultiError,
// or nil if none found.
func (m *PreSignedReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PreSignedReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uri

	if len(errors) > 0 {
		return PreSignedReplyMultiError(errors)
	}

	return nil
}

// PreSignedReplyMultiError is an error wrapping multiple validation errors
// returned by PreSignedReply.ValidateAll() if the designated constraints
// aren't met.
type PreSignedReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreSignedReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreSignedReplyMultiError) AllErrors() []error { return m }

// PreSignedReplyValidationError is the validation error returned by
// PreSignedReply.Validate if the designated constraints aren't met.
type PreSignedReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreSignedReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreSignedReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreSignedReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreSignedReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreSignedReplyValidationError) ErrorName() string { return "PreSignedReplyValidationError" }

// Error satisfies the builtin error interface
func (e PreSignedReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreSignedReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreSignedReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreSignedReplyValidationError{}
