// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: oss-proto/oss.proto

package oss

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PreSignedRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PreSignedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreSignedRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreSignedRequestMultiError, or nil if none found.
func (m *PreSignedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PreSignedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Category

	// no validation rules for Name

	if len(errors) > 0 {
		return PreSignedRequestMultiError(errors)
	}

	return nil
}

// PreSignedRequestMultiError is an error wrapping multiple validation errors
// returned by PreSignedRequest.ValidateAll() if the designated constraints
// aren't met.
type PreSignedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreSignedRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreSignedRequestMultiError) AllErrors() []error { return m }

// PreSignedRequestValidationError is the validation error returned by
// PreSignedRequest.Validate if the designated constraints aren't met.
type PreSignedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreSignedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreSignedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreSignedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreSignedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreSignedRequestValidationError) ErrorName() string { return "PreSignedRequestValidationError" }

// Error satisfies the builtin error interface
func (e PreSignedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreSignedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreSignedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreSignedRequestValidationError{}

// Validate checks the field values on PreSignedReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PreSignedReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreSignedReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PreSignedReplyMultiError,
// or nil if none found.
func (m *PreSignedReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PreSignedReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uri

	if len(errors) > 0 {
		return PreSignedReplyMultiError(errors)
	}

	return nil
}

// PreSignedReplyMultiError is an error wrapping multiple validation errors
// returned by PreSignedReply.ValidateAll() if the designated constraints
// aren't met.
type PreSignedReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreSignedReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreSignedReplyMultiError) AllErrors() []error { return m }

// PreSignedReplyValidationError is the validation error returned by
// PreSignedReply.Validate if the designated constraints aren't met.
type PreSignedReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreSignedReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreSignedReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreSignedReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreSignedReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreSignedReplyValidationError) ErrorName() string { return "PreSignedReplyValidationError" }

// Error satisfies the builtin error interface
func (e PreSignedReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreSignedReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreSignedReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreSignedReplyValidationError{}

// Validate checks the field values on OcrRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OcrRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OcrRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OcrRequestMultiError, or
// nil if none found.
func (m *OcrRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OcrRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Category != nil {
		// no validation rules for Category
	}

	if m.Threshold != nil {
		// no validation rules for Threshold
	}

	if len(errors) > 0 {
		return OcrRequestMultiError(errors)
	}

	return nil
}

// OcrRequestMultiError is an error wrapping multiple validation errors
// returned by OcrRequest.ValidateAll() if the designated constraints aren't met.
type OcrRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OcrRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OcrRequestMultiError) AllErrors() []error { return m }

// OcrRequestValidationError is the validation error returned by
// OcrRequest.Validate if the designated constraints aren't met.
type OcrRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrRequestValidationError) ErrorName() string { return "OcrRequestValidationError" }

// Error satisfies the builtin error interface
func (e OcrRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrRequestValidationError{}

// Validate checks the field values on OcrDetail with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OcrDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OcrDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OcrDetailMultiError, or nil
// if none found.
func (m *OcrDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *OcrDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Original

	// no validation rules for Msg

	// no validation rules for ParseLatency

	for idx, item := range m.GetPoints() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OcrDetailValidationError{
						field:  fmt.Sprintf("Points[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OcrDetailValidationError{
						field:  fmt.Sprintf("Points[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OcrDetailValidationError{
					field:  fmt.Sprintf("Points[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DetLatency != nil {
		// no validation rules for DetLatency
	}

	if m.ClsLatency != nil {
		// no validation rules for ClsLatency
	}

	if m.RecLatency != nil {
		// no validation rules for RecLatency
	}

	if len(errors) > 0 {
		return OcrDetailMultiError(errors)
	}

	return nil
}

// OcrDetailMultiError is an error wrapping multiple validation errors returned
// by OcrDetail.ValidateAll() if the designated constraints aren't met.
type OcrDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OcrDetailMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OcrDetailMultiError) AllErrors() []error { return m }

// OcrDetailValidationError is the validation error returned by
// OcrDetail.Validate if the designated constraints aren't met.
type OcrDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrDetailValidationError) ErrorName() string { return "OcrDetailValidationError" }

// Error satisfies the builtin error interface
func (e OcrDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrDetailValidationError{}

// Validate checks the field values on OcrPoint with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OcrPoint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OcrPoint with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OcrPointMultiError, or nil
// if none found.
func (m *OcrPoint) ValidateAll() error {
	return m.validate(true)
}

func (m *OcrPoint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TextRegion

	// no validation rules for Confidence

	// no validation rules for Text

	if len(errors) > 0 {
		return OcrPointMultiError(errors)
	}

	return nil
}

// OcrPointMultiError is an error wrapping multiple validation errors returned
// by OcrPoint.ValidateAll() if the designated constraints aren't met.
type OcrPointMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OcrPointMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OcrPointMultiError) AllErrors() []error { return m }

// OcrPointValidationError is the validation error returned by
// OcrPoint.Validate if the designated constraints aren't met.
type OcrPointValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrPointValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrPointValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrPointValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrPointValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrPointValidationError) ErrorName() string { return "OcrPointValidationError" }

// Error satisfies the builtin error interface
func (e OcrPointValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrPoint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrPointValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrPointValidationError{}

// Validate checks the field values on OcrReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OcrReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OcrReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OcrReplyMultiError, or nil
// if none found.
func (m *OcrReply) ValidateAll() error {
	return m.validate(true)
}

func (m *OcrReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OcrReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OcrReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OcrReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Latency

	if len(errors) > 0 {
		return OcrReplyMultiError(errors)
	}

	return nil
}

// OcrReplyMultiError is an error wrapping multiple validation errors returned
// by OcrReply.ValidateAll() if the designated constraints aren't met.
type OcrReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OcrReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OcrReplyMultiError) AllErrors() []error { return m }

// OcrReplyValidationError is the validation error returned by
// OcrReply.Validate if the designated constraints aren't met.
type OcrReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrReplyValidationError) ErrorName() string { return "OcrReplyValidationError" }

// Error satisfies the builtin error interface
func (e OcrReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrReplyValidationError{}
