// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: oss-proto/oss.proto

package oss

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Oss_PreSigned_FullMethodName = "/oss.v1.Oss/PreSigned"
	Oss_Ocr_FullMethodName       = "/oss.v1.Oss/Ocr"
)

// OssClient is the client API for Oss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OssClient interface {
	PreSigned(ctx context.Context, in *PreSignedRequest, opts ...grpc.CallOption) (*PreSignedReply, error)
	Ocr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrReply, error)
}

type ossClient struct {
	cc grpc.ClientConnInterface
}

func NewOssClient(cc grpc.ClientConnInterface) OssClient {
	return &ossClient{cc}
}

func (c *ossClient) PreSigned(ctx context.Context, in *PreSignedRequest, opts ...grpc.CallOption) (*PreSignedReply, error) {
	out := new(PreSignedReply)
	err := c.cc.Invoke(ctx, Oss_PreSigned_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ossClient) Ocr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrReply, error) {
	out := new(OcrReply)
	err := c.cc.Invoke(ctx, Oss_Ocr_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OssServer is the server API for Oss service.
// All implementations must embed UnimplementedOssServer
// for forward compatibility
type OssServer interface {
	PreSigned(context.Context, *PreSignedRequest) (*PreSignedReply, error)
	Ocr(context.Context, *OcrRequest) (*OcrReply, error)
	mustEmbedUnimplementedOssServer()
}

// UnimplementedOssServer must be embedded to have forward compatible implementations.
type UnimplementedOssServer struct {
}

func (UnimplementedOssServer) PreSigned(context.Context, *PreSignedRequest) (*PreSignedReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreSigned not implemented")
}
func (UnimplementedOssServer) Ocr(context.Context, *OcrRequest) (*OcrReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ocr not implemented")
}
func (UnimplementedOssServer) mustEmbedUnimplementedOssServer() {}

// UnsafeOssServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OssServer will
// result in compilation errors.
type UnsafeOssServer interface {
	mustEmbedUnimplementedOssServer()
}

func RegisterOssServer(s grpc.ServiceRegistrar, srv OssServer) {
	s.RegisterService(&Oss_ServiceDesc, srv)
}

func _Oss_PreSigned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSignedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServer).PreSigned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oss_PreSigned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServer).PreSigned(ctx, req.(*PreSignedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oss_Ocr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OcrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServer).Ocr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oss_Ocr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServer).Ocr(ctx, req.(*OcrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oss_ServiceDesc is the grpc.ServiceDesc for Oss service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oss_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oss.v1.Oss",
	HandlerType: (*OssServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreSigned",
			Handler:    _Oss_PreSigned_Handler,
		},
		{
			MethodName: "Ocr",
			Handler:    _Oss_Ocr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oss-proto/oss.proto",
}
