// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v4.25.0
// source: oss-proto/oss.proto

package oss

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOssPreSigned = "/oss.v1.Oss/PreSigned"

type OssHTTPServer interface {
	PreSigned(context.Context, *PreSignedRequest) (*PreSignedReply, error)
}

func RegisterOssHTTPServer(s *http.Server, srv OssHTTPServer) {
	r := s.Route("/")
	r.POST("/pre/signed", _Oss_PreSigned0_HTTP_Handler(srv))
}

func _Oss_PreSigned0_HTTP_Handler(srv OssHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreSignedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOssPreSigned)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreSigned(ctx, req.(*PreSignedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreSignedReply)
		return ctx.Result(200, reply)
	}
}

type OssHTTPClient interface {
	PreSigned(ctx context.Context, req *PreSignedRequest, opts ...http.CallOption) (rsp *PreSignedReply, err error)
}

type OssHTTPClientImpl struct {
	cc *http.Client
}

func NewOssHTTPClient(client *http.Client) OssHTTPClient {
	return &OssHTTPClientImpl{client}
}

func (c *OssHTTPClientImpl) PreSigned(ctx context.Context, in *PreSignedRequest, opts ...http.CallOption) (*PreSignedReply, error) {
	var out PreSignedReply
	pattern := "/pre/signed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOssPreSigned))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
