// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"oss/internal/data/model"
)

func newOss(db *gorm.DB, opts ...gen.DOOption) oss {
	_oss := oss{}

	_oss.ossDo.UseDB(db, opts...)
	_oss.ossDo.UseModel(&model.Oss{})

	tableName := _oss.ossDo.TableName()
	_oss.ALL = field.NewAsterisk(tableName)
	_oss.ID = field.NewUint64(tableName, "id")
	_oss.CreatedAt = field.NewField(tableName, "created_at")
	_oss.UpdatedAt = field.NewField(tableName, "updated_at")
	_oss.Name = field.NewString(tableName, "name")

	_oss.fillFieldMap()

	return _oss
}

type oss struct {
	ossDo ossDo

	ALL       field.Asterisk
	ID        field.Uint64 // auto increment id
	CreatedAt field.Field  // create time
	UpdatedAt field.Field  // update time
	Name      field.String // name

	fieldMap map[string]field.Expr
}

func (g oss) Table(newTableName string) *oss {
	g.ossDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g oss) As(alias string) *oss {
	g.ossDo.DO = *(g.ossDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *oss) updateTableName(table string) *oss {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.CreatedAt = field.NewField(table, "created_at")
	g.UpdatedAt = field.NewField(table, "updated_at")
	g.Name = field.NewString(table, "name")

	g.fillFieldMap()

	return g
}

func (g *oss) WithContext(ctx context.Context) *ossDo { return g.ossDo.WithContext(ctx) }

func (g oss) TableName() string { return g.ossDo.TableName() }

func (g oss) Alias() string { return g.ossDo.Alias() }

func (g oss) Columns(cols ...field.Expr) gen.Columns { return g.ossDo.Columns(cols...) }

func (g *oss) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *oss) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["id"] = g.ID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["name"] = g.Name
}

func (g oss) clone(db *gorm.DB) oss {
	g.ossDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g oss) replaceDB(db *gorm.DB) oss {
	g.ossDo.ReplaceDB(db)
	return g
}

type ossDo struct{ gen.DO }

// SELECT * FROM `@@table` WHERE `id` = @id LIMIT 1
func (g ossDo) GetByID(id uint64) (result model.Oss) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM `oss` WHERE `id` = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (g ossDo) GetByCol(col string, val string) (result model.Oss) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `oss` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (g ossDo) GetByCols(cols []string, vals []string) (result model.Oss) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `oss` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
func (g ossDo) FindByCol(col string, val string) (result []model.Oss) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `oss` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(g.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
func (g ossDo) FindByCols(cols []string, vals []string) (result []model.Oss) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `oss` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(g.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

func (g ossDo) Debug() *ossDo {
	return g.withDO(g.DO.Debug())
}

func (g ossDo) WithContext(ctx context.Context) *ossDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g ossDo) ReadDB() *ossDo {
	return g.Clauses(dbresolver.Read)
}

func (g ossDo) WriteDB() *ossDo {
	return g.Clauses(dbresolver.Write)
}

func (g ossDo) Session(config *gorm.Session) *ossDo {
	return g.withDO(g.DO.Session(config))
}

func (g ossDo) Clauses(conds ...clause.Expression) *ossDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g ossDo) Returning(value interface{}, columns ...string) *ossDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g ossDo) Not(conds ...gen.Condition) *ossDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g ossDo) Or(conds ...gen.Condition) *ossDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g ossDo) Select(conds ...field.Expr) *ossDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g ossDo) Where(conds ...gen.Condition) *ossDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g ossDo) Order(conds ...field.Expr) *ossDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g ossDo) Distinct(cols ...field.Expr) *ossDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g ossDo) Omit(cols ...field.Expr) *ossDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g ossDo) Join(table schema.Tabler, on ...field.Expr) *ossDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g ossDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ossDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g ossDo) RightJoin(table schema.Tabler, on ...field.Expr) *ossDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g ossDo) Group(cols ...field.Expr) *ossDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g ossDo) Having(conds ...gen.Condition) *ossDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g ossDo) Limit(limit int) *ossDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g ossDo) Offset(offset int) *ossDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g ossDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ossDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g ossDo) Unscoped() *ossDo {
	return g.withDO(g.DO.Unscoped())
}

func (g ossDo) Create(values ...*model.Oss) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g ossDo) CreateInBatches(values []*model.Oss, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g ossDo) Save(values ...*model.Oss) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g ossDo) First() (*model.Oss, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oss), nil
	}
}

func (g ossDo) Take() (*model.Oss, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oss), nil
	}
}

func (g ossDo) Last() (*model.Oss, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oss), nil
	}
}

func (g ossDo) Find() ([]*model.Oss, error) {
	result, err := g.DO.Find()
	return result.([]*model.Oss), err
}

func (g ossDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Oss, err error) {
	buf := make([]*model.Oss, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g ossDo) FindInBatches(result *[]*model.Oss, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g ossDo) Attrs(attrs ...field.AssignExpr) *ossDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g ossDo) Assign(attrs ...field.AssignExpr) *ossDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g ossDo) Joins(fields ...field.RelationField) *ossDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g ossDo) Preload(fields ...field.RelationField) *ossDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g ossDo) FirstOrInit() (*model.Oss, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oss), nil
	}
}

func (g ossDo) FirstOrCreate() (*model.Oss, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oss), nil
	}
}

func (g ossDo) FindByPage(offset int, limit int) (result []*model.Oss, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g ossDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g ossDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g ossDo) Delete(models ...*model.Oss) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *ossDo) withDO(do gen.Dao) *ossDo {
	g.DO = *do.(*gen.DO)
	return g
}
