// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/golang-module/carbon/v2"
)

const TableNameOss = "oss"

// Oss mapped from table <oss>
type Oss struct {
	ID        uint64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"` // auto increment id
	CreatedAt carbon.DateTime `gorm:"column:created_at;comment:create time" json:"createdAt"`                             // create time
	UpdatedAt carbon.DateTime `gorm:"column:updated_at;comment:update time" json:"updatedAt"`                             // update time
	Name      string          `gorm:"column:name;comment:name" json:"name"`                                               // name
}

// TableName Oss's table name
func (*Oss) TableName() string {
	return TableNameOss
}
